services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false

before_install:
- docker pull firedrakeproject/firedrake

script:
- docker run --rm -P -v `pwd`:/home/firedrake/sapphire-ice -w /home/firedrake/sapphire-ice  firedrakeproject/firedrake "ls && . firedrake/bin/activate && python3 setup.py install && python3 -m pytest -v ." 
