services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false

before_install:
- docker pull firedrakeproject/firedrake

script:
- docker run -dti -P -v `pwd`:/home/firedrake/sapphire-ice -w /home/firedrake/ --name fd firedrakeproject/firedrake
- docker exec -u firedrake fd "ls"
- docker exec -u firedrake fd "git clone https://github.com/geo-fluid-dynamics/sapphire.git"
- docker exec -u firedrake fd ". firedrake/bin/activate && cd sapphire && python3 setup.py install"
- docker exec -u firedrake fd ". firedrake/bin/activate && cd sapphire-ice && python3 setup.py install"
- docker exec -u firedrake fd ". firedrake/bin/activate && python3 -m pytest -v sapphire-ice"
